import {existsSync} from 'node:fs';
import {loadEnvFile} from 'node:process';
import {fetchSnapshot} from '../dashboard/lib/gateway.mjs';
import {fetchAddress,DEFAULT_ADDRESS} from '../dashboard/lib/address.mjs';
if(existsSync('.env'))loadEnvFile('.env');
const config={base:process.env.BLOCKCHAIN_API_BASE_URL,key:process.env.BLOCKCHAIN_API_KEY?.trim()};
const address=await fetchAddress(DEFAULT_ADDRESS,0,config);
console.log(JSON.stringify({kind:'address',authenticated:address.authenticated,summary:address.summary,quality:address.transactions?.quality,errors:address.errors},null,2));
const snapshot=await fetchSnapshot(30,{base:config.base,key:undefined});
console.log(JSON.stringify({source:snapshot.source,authenticated:snapshot.authenticated,fetchedAt:snapshot.fetchedAt,series:snapshot.series.map(s=>({id:s.id,unit:s.unit,period:s.period,quality:s.quality,schema:s.schema,first:s.values[0],last:s.values.at(-1)})),errors:snapshot.errors},null,2));
if(snapshot.errors.length||address.errors.length)process.exitCode=1;
